/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gamarra.tiendacalzados.ui;

import javax.swing.JFrame;

/**
 *
 * @author Sistema
 */
public class PrincipalUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalUI.class.getName());

    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        initConfig();
    }
    
    private void initConfig(){                             // EL initConfig() DEBE ESTAR EN EL CONSTRUTOR: PrincipalUI
        this.setTitle("Sistema Tienda de Calzados");      // ASIGNAMOS EL TITUTO AL FORMULARIO: PrincipalUI       
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);    // MAXIMIZAMOS EL FORMULARIO: PrincipalUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAgregarProducto = new javax.swing.JMenuItem();
        mnEliminarProducto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnNuevaVenta = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnReporteVentas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlDesktopLayout = new javax.swing.GroupLayout(pnlDesktop);
        pnlDesktop.setLayout(pnlDesktopLayout);
        pnlDesktopLayout.setHorizontalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        pnlDesktopLayout.setVerticalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/Archivo.png"))); // NOI18N
        mnSalir.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/Salir.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        mnSalir.add(jMenuItem1);

        jMenuBar1.add(mnSalir);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/Productos.png"))); // NOI18N
        jMenu2.setText("Productos");

        mnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/Agregar.png"))); // NOI18N
        mnAgregarProducto.setText("Agregar Producto");
        mnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(mnAgregarProducto);

        mnEliminarProducto.setText("Eliminar Producto");
        mnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(mnEliminarProducto);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/Ventas.png"))); // NOI18N
        jMenu3.setText("Ventas");

        mnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/NuevaVenta.png"))); // NOI18N
        mnNuevaVenta.setText("Nueva Venta");
        jMenu3.add(mnNuevaVenta);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/Reportes.png"))); // NOI18N
        jMenu4.setText("Reportes");

        mnReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamarra/tiendacalzados/assets/images/ReporteVentas.png"))); // NOI18N
        mnReporteVentas.setText("Reporte Ventas");
        jMenu4.add(mnReporteVentas);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarProductoActionPerformed
              AgregaProductosUI agregaProductosUI = new AgregaProductosUI();
              agregaProductosUI.setVisible(true);
              pnlDesktop.add(agregaProductosUI);

    }//GEN-LAST:event_mnAgregarProductoActionPerformed

    private void mnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarProductoActionPerformed
              EliminarProductosUI eliminarProductosUI = new EliminarProductosUI();
              eliminarProductosUI.setVisible(true);
              pnlDesktop.add(eliminarProductosUI);
    }//GEN-LAST:event_mnEliminarProductoActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnAgregarProducto;
    private javax.swing.JMenuItem mnEliminarProducto;
    private javax.swing.JMenu mnNuevaVenta;
    private javax.swing.JMenu mnReporteVentas;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JDesktopPane pnlDesktop;
    // End of variables declaration//GEN-END:variables
}
